# SPDX-License-Identifier: FSL-1.1-MIT
version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
