#!/usr/bin/env bash

DC="${DC:-exec}"

# If we're running in CI we need to disable TTY allocation for docker-compose
# commands that enable it by default, such as exec and run.
TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _dc {
  docker-compose "${DC}" ${TTY} "${@}"
}

# -----------------------------------------------------------------------------

function cmd {
  # Run any command you want in the web container
  _dc web "${@}"
}

function manage {
  # Run any manage.py commands

  # We need to collectstatic before we run our tests.
  if [ "${1-''}" == "test" ]; then
    cmd python manage.py collectstatic --no-input
  fi

  cmd python manage.py "${@}"
}

function test {
  # Run pytest commands

  cmd pytest "${@}"
}

function black {
  # Run Black code formatter check
  cmd black "${@}"
}

function flake8 {
  # Lint Python code with flake8
  cmd flake8 "${@}"
}

function isort {
  # Sort imports with isort
  cmd isort "${@}"
}


function ci:test {
  cp --no-clobber .env.example .env

  docker-compose build
  docker-compose up -d

  . .env

  manage check
  isort --check --profile black .
  black --check .
  flake8 .
  manage migrate
  test
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
