# Generated by Django 3.2.4 on 2021-06-17 14:44

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0002_chain_transaction_service_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="theme_background_color",
            field=models.CharField(
                default="#000",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#(?:[0-9a-fA-F]{3,4}){1,2}$"),
                        "Invalid hex color",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="chain",
            name="theme_text_color",
            field=models.CharField(
                default="#fff",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#(?:[0-9a-fA-F]{3,4}){1,2}$"),
                        "Invalid hex color",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
