# Generated by Django 3.2.4 on 2021-06-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0003_auto_20210617_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="gas_price_oracle_parameter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chain",
            name="gas_price_oracle_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
