# Generated by Django 3.2.5 on 2021-07-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0007_chain_currency_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="ens_registry_address",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
