# Generated by Django 3.2.5 on 2021-07-12 13:47

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0009_chain_gas_price_oracle_gwei_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="min_master_copy_version",
            field=models.CharField(
                default="1.3.0",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(
                            "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"  # noqa E501
                        ),
                        "Invalid version (semver)",
                        "invalid",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
