# Generated by Django 3.2.5 on 2021-07-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0014_alter_chain_transaction_service_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="currency_name",
            field=models.CharField(max_length=255),
        ),
    ]
