# Generated by Django 3.2.5 on 2021-07-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0015_alter_chain_currency_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="block_explorer_uri",
            field=models.URLField(blank=True, null=True),
        ),
    ]
