# Generated by Django 3.2.5 on 2021-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0016_alter_chain_block_explorer_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="block_explorer_uri",
            field=models.URLField(),
        ),
    ]
