# Generated by Django 3.2.5 on 2021-07-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0017_alter_chain_block_explorer_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="rpc_authentication",
            field=models.CharField(
                choices=[
                    ("API_KEY_PATH", "Api Key Path"),
                    ("NO_AUTHENTICATION", "No Authentication"),
                ],
                default="API_KEY_PATH",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
