# Generated by Django 3.2.5 on 2021-07-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0017_alter_chain_block_explorer_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='safe_apps_rpc_uri',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
