# Generated by Django 3.2.5 on 2021-07-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0018_chain_rpc_authentication"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="safe_apps_rpc_uri",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
