# Generated by Django 3.2.6 on 2021-08-03 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0021_alter_chain_safe_apps_rpc_authentication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chain",
            name="block_explorer_uri",
        ),
    ]
