# Generated by Django 3.2.6 on 2021-09-01 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0023_create_gas_price_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chain",
            name="gas_price_fixed_wei",
        ),
        migrations.RemoveField(
            model_name="chain",
            name="gas_price_oracle_gwei_factor",
        ),
        migrations.RemoveField(
            model_name="chain",
            name="gas_price_oracle_parameter",
        ),
        migrations.RemoveField(
            model_name="chain",
            name="gas_price_oracle_uri",
        ),
    ]
