# Generated by Django 3.2.7 on 2021-09-06 15:05

from django.db import migrations, models

import chains.models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0024_remove_gas_price_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="currency_logo_uri",
            field=models.ImageField(
                max_length=255, upload_to=chains.models.native_currency_path
            ),
        ),
    ]
