# Generated by Django 3.2.7 on 2021-09-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0025_alter_chain_currency_logo_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="l2",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
