# Generated by Django 3.2.7 on 2021-09-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0026_chain_l2"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
