# Generated by Django 3.2.7 on 2021-09-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0027_chain_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="vpc_transaction_service_uri",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
