# Generated by Django 3.2.9 on 2021-11-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0029_chain_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "chains",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Chains where this wallet is enabled.",
                        to="chains.Chain",
                    ),
                ),
            ],
        ),
    ]
