# Generated by Django 3.2.9 on 2021-11-05 10:21
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations import RunPython

from chains.models import Feature

DEFAULT_FEATURES = [
    Feature(key="CONTRACT_INTERACTION"),
    Feature(key="DOMAIN_LOOKUP"),
    Feature(key="ERC721"),
    Feature(key="ERC1155"),
    Feature(key="SAFE_APPS"),
    Feature(key="SPENDING_LIMIT"),
]


def add_default_features(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Feature = apps.get_model("chains", "Feature")
    Feature.objects.bulk_create(DEFAULT_FEATURES)


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0031_chain_block_explorer_uri_api_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The unique name/key that identifies this feature",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "chains",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Chains where this feature is enabled.",
                        to="chains.Chain",
                    ),
                ),
            ],
        ),
        # Adds default features without assigning chains to them
        migrations.RunPython(add_default_features, RunPython.noop),
    ]
