# Generated by Django 3.2.9 on 2021-11-03 14:29
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations import RunPython

from ..models import Feature

DEFAULT_FEATURES = [
    Feature(name="CONTRACT_INTERACTION"),
    Feature(name="DOMAIN_LOOKUP"),
    Feature(name="ERC721"),
    Feature(name="ERC1155"),
    Feature(name="SAFE_APPS"),
    Feature(name="SPENDING_LIMIT"),
]


def add_default_features(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Feature = apps.get_model("chains", "Feature")
    Feature.objects.bulk_create(DEFAULT_FEATURES)


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0031_chain_block_explorer_uri_api_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "chains",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Chains where this feature is enabled.",
                        to="chains.Chain",
                    ),
                ),
            ],
        ),
        # Adds default features without assigning chains to them
        migrations.RunPython(add_default_features, RunPython.noop),
    ]
