# Generated by Django 3.2.9 on 2021-11-30 14:03
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.models import F


def copy_rpc_fields(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    chain_model = apps.get_model("chains", "Chain")
    db_alias = schema_editor.connection.alias
    chain_model.objects.using(db_alias).all().update(
        public_rpc_uri=F("rpc_uri"),
        public_rpc_authentication=F("rpc_authentication"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0033_walletnew"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="public_rpc_authentication",
            field=models.CharField(
                choices=[
                    ("API_KEY_PATH", "Api Key Path"),
                    ("NO_AUTHENTICATION", "No Authentication"),
                ],
                default="NO_AUTHENTICATION",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="chain",
            name="public_rpc_uri",
            field=models.URLField(null=True),
            preserve_default=False,
        ),
        migrations.RunPython(copy_rpc_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="chain",
            name="public_rpc_uri",
            field=models.URLField(null=False, blank=False),
            preserve_default=False,
        ),
    ]
