# Generated by Django 3.2.10 on 2021-12-24 12:26

from django.db import migrations, models

import chains.models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0034_add_public_rpc_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="currency_logo_uri",
            field=models.ImageField(
                max_length=255,
                upload_to=chains.models.native_currency_path,
                validators=[chains.models.validate_native_currency_size],
            ),
        ),
    ]
