# Generated by Django 4.0.3 on 2022-03-23 09:39

from django.db import migrations, models

import chains.models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0035_alter_chain_currency_logo_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="transaction_service_uri",
            field=models.CharField(
                max_length=255, validators=[chains.models.validate_tx_service_url]
            ),
        ),
        migrations.AlterField(
            model_name="chain",
            name="vpc_transaction_service_uri",
            field=models.CharField(
                max_length=255, validators=[chains.models.validate_tx_service_url]
            ),
        ),
    ]
