# Generated by Django 4.0.5 on 2023-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0036_alter_chain_transaction_service_uri_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
