# Generated by Django 4.0.5 on 2022-10-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0036_alter_chain_transaction_service_uri_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="warning",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
