# Generated by Django 5.0.1 on 2024-01-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0038_gasprice_max_fee_per_gas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="is_testnet",
            field=models.BooleanField(default=False),
        ),
    ]
