# Generated by Django 4.2.4 on 2023-08-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0038_gasprice_max_fee_per_gas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="ens_registry_address",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gasprice",
            name="fixed_wei_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=79,
                null=True,
                verbose_name="Fixed gas price (wei)",
            ),
        ),
        migrations.AlterField(
            model_name="gasprice",
            name="max_fee_per_gas",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=79,
                null=True,
                verbose_name="Max fee per gas (wei)",
            ),
        ),
        migrations.AlterField(
            model_name="gasprice",
            name="max_priority_fee_per_gas",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=79,
                null=True,
                verbose_name="Max priority fee per gas (wei)",
            ),
        ),
    ]
