# Generated by Django 5.0.1 on 2024-02-01 09:24

import chains.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0039_chain_is_testnet"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="chain_logo_uri",
            field=models.ImageField(
                default="",
                max_length=255,
                upload_to=chains.models.chain_logo_path,
                validators=[chains.models.validate_native_currency_size],
            ),
        ),
    ]
