# Generated by Django 5.0.1 on 2024-02-08 14:49

from django.db import migrations, models

import chains.models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0039_chain_is_testnet"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="chain_logo_uri",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=chains.models.chain_logo_path,
                validators=[chains.models.validate_native_currency_size],
            ),
        ),
    ]
