# Generated by Django 4.2.2 on 2024-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0040_chain_chain_logo_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="prices_provider_chain_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chain",
            name="prices_provider_native_coin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
