# Generated by Django 5.0.6 on 2024-07-10 14:14

import gnosis.eth.django.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0042_chain_balances_provider_chain_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="create_call_address",
            field=gnosis.eth.django.models.EthereumAddressField(
                blank=True, null=True
            ),  # type: ignore[no-untyped-call]
        ),
        migrations.AddField(
            model_name="chain",
            name="fallback_handler_address",
            field=gnosis.eth.django.models.EthereumAddressField(
                blank=True, null=True
            ),  # type: ignore[no-untyped-call]
        ),
        migrations.AddField(
            model_name="chain",
            name="multi_send_address",
            field=gnosis.eth.django.models.EthereumAddressField(
                blank=True, null=True
            ),  # type: ignore[no-untyped-call]
        ),
        migrations.AddField(
            model_name="chain",
            name="multi_send_call_only_address",
            field=gnosis.eth.django.models.EthereumAddressField(
                blank=True, null=True
            ),  # type: ignore[no-untyped-call]
        ),
        migrations.AddField(
            model_name="chain",
            name="safe_proxy_factory_address",
            field=gnosis.eth.django.models.EthereumAddressField(
                blank=True, null=True
            ),  # type: ignore[no-untyped-call]
        ),
        migrations.AddField(
            model_name="chain",
            name="safe_singleton_address",
            field=gnosis.eth.django.models.EthereumAddressField(
                blank=True, null=True
            ),  # type: ignore[no-untyped-call]
        ),
        migrations.AddField(
            model_name="chain",
            name="sign_message_lib_address",
            field=gnosis.eth.django.models.EthereumAddressField(
                blank=True, null=True
            ),  # type: ignore[no-untyped-call]
        ),
        migrations.AddField(
            model_name="chain",
            name="simulate_tx_accessor_address",
            field=gnosis.eth.django.models.EthereumAddressField(
                blank=True, null=True
            ),  # type: ignore[no-untyped-call]
        ),
        migrations.AddField(
            model_name="chain",
            name="safe_web_authn_signer_factory_address",
            field=gnosis.eth.django.models.EthereumAddressField(
                blank=True, null=True
            ),  # type: ignore[no-untyped-call]
        ),
    ]
