# Generated by Django 5.0.8 on 2024-09-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0043_chain_create_call_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="beacon_chain_explorer_uri_public_key_template",
            field=models.URLField(blank=True, null=True),
        ),
    ]
