# Generated by Django 5.0.8 on 2024-11-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0044_chain_beacon_chain_explorer_uri_public_key_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="description",
            field=models.CharField(max_length=255, default=''),
        ),
    ]
