# Generated by Django 5.0.8 on 2024-11-21 12:22

from django.db import migrations

def populate_description(apps, schema_editor):
    Feature = apps.get_model('chains', 'Feature')
    Feature.objects.filter(description__isnull=True).update(description='')

def reverse_populate_description(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0044_chain_beacon_chain_explorer_uri_public_key_template'),
    ]

    operations = [
        migrations.RunPython(populate_description, reverse_populate_description),
    ]
