# Generated by Django 5.1.5 on 2025-03-27 12:47

import safe_eth.eth.django.models
from django.db import migrations


FIELDS = [
    "create_call_address",
    "ens_registry_address",
    "fallback_handler_address",
    "multi_send_address",
    "multi_send_call_only_address",
    "safe_proxy_factory_address",
    "safe_singleton_address",
    "safe_web_authn_signer_factory_address",
    "sign_message_lib_address",
    "simulate_tx_accessor_address",
]

def sql_cast_fields_to_bytea() -> str:
    return "\n".join(
        f"""ALTER TABLE chains_chain
            ALTER COLUMN "{field}" TYPE bytea
            USING DECODE(SUBSTRING("{field}", 3), 'hex');"""
        for field in FIELDS
    )

class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0045_populate_feature_description'),
    ]

    operations = [
        migrations.RunSQL(
            sql_cast_fields_to_bytea(),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='chain',
            name='create_call_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='ens_registry_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='fallback_handler_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='multi_send_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='multi_send_call_only_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='safe_proxy_factory_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='safe_singleton_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='safe_web_authn_signer_factory_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='sign_message_lib_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='simulate_tx_accessor_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
    ]
