# Generated by Django 5.1.4 on 2024-12-10 09:34

import safe_eth.eth.django.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0045_populate_feature_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='create_call_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='ens_registry_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='fallback_handler_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='multi_send_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='multi_send_call_only_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='safe_proxy_factory_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='safe_singleton_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='safe_web_authn_signer_factory_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='sign_message_lib_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='simulate_tx_accessor_address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, null=True),
        ),
    ]
