# Generated by Django 5.1.5 on 2025-04-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0046_alter_chain_create_call_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='zk',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            """
            UPDATE chains_chain
            SET zk = TRUE
            WHERE id IN (
                -- Lens
                232,
                -- zkSync
                324
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
