# Generated by Django 5.1.5 on 2025-04-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0046_alter_chain_create_call_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='zk',
            field=models.BooleanField(default=False),
        ),
    ]
