# Generated by Django 6.0.1 on 2026-02-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0047_chain_zk'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='enable_by_default',
            field=models.BooleanField(default=False, help_text='If checked, this feature will be automatically enabled when creating a chain.'),
        ),
    ]
