# Generated by Django 5.1.5 on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0048_feature_enable_by_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="enable_by_default",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this wallet will be automatically enabled when creating a new chain.",
            ),
        ),
    ]
