# Generated by Django 6.0.1 on 2026-02-04 09:10

import chains.models
import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0049_wallet_enable_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='block_explorer_uri_address_template',
            field=models.URLField(default='https://placeholderURL/address/{{address}}', help_text='Please replace placeholderURL by the block explorer base URL'),
        ),
        migrations.AlterField(
            model_name='chain',
            name='block_explorer_uri_api_template',
            field=models.URLField(default='https://placeholderURL/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}', help_text='Please replace placeholderURL by the block explorer base URL'),
        ),
        migrations.AlterField(
            model_name='chain',
            name='block_explorer_uri_tx_hash_template',
            field=models.URLField(default='https://placeholderURL/tx/{{txHash}}', help_text='Please replace placeholderURL by the block explorer base URL'),
        ),
        migrations.AlterField(
            model_name='chain',
            name='recommended_master_copy_version',
            field=models.CharField(default='1.4.1', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$'), 'Invalid version (semver)', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='chain',
            name='vpc_transaction_service_uri',
            field=models.CharField(default='http://staging-chain-safe-transaction-web.safe-transaction-chain.svc.cluster.local', help_text='Please replace chain by chain name and delete staging if production environment', max_length=255, validators=[chains.models.validate_tx_service_url]),
        ),
    ]
