# Generated by Django 6.0.2 on 2026-02-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0052_feature_scope_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='enable_by_default',
        ),
    ]
