# SPDX-License-Identifier: FSL-1.1-MIT
# Generated by Django 6.0.2 on 2026-03-18 12:11

import chains.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0053_remove_feature_enable_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='vpc_rpc_uri',
            field=models.CharField(default='http://chain-rpc-haproxy.safe-transaction-chain.svc.cluster.local:8545', help_text='Please replace chain by chain name', max_length=255, validators=[chains.models.validate_url]),
        ),
    ]
