# Generated by Django 6.0.1 on 2026-03-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0054_chain_vpc_rpc_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='create_call_address',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='fallback_handler_address',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='multi_send_address',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='multi_send_call_only_address',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='safe_proxy_factory_address',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='safe_singleton_address',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='safe_web_authn_signer_factory_address',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='sign_message_lib_address',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='simulate_tx_accessor_address',
        ),
    ]
