# SPDX-License-Identifier: FSL-1.1-MIT
# Generated by Django 6.0.4 on 2026-05-20 07:21

import safe_eth.eth.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0054_chain_vpc_rpc_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', safe_eth.eth.django.models.EthereumAddressBinaryField(help_text='Token contract address.', unique=True)),
                ('symbol', models.CharField(max_length=50)),
                ('chains', models.ManyToManyField(blank=True, help_text='Chains where this token is accepted as a fee payment.', to='chains.chain')),
            ],
            options={
                'unique_together': {('address', 'symbol')},
            },
        ),
    ]
