# SPDX-License-Identifier: FSL-1.1-MIT
# Generated by Django 6.0.5 on 2026-06-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0056_chain_relayer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='relayer_safe_creation_sponsored',
            field=models.BooleanField(db_default=False, default=False, help_text='Sponsor/relay Safe account creation transactions. Requires a relayer type.'),
        ),
        migrations.AddField(
            model_name='chain',
            name='relayer_safe_transaction_sponsored',
            field=models.BooleanField(db_default=False, default=False, help_text='Sponsor/relay Safe transaction execution. Requires a relayer type.'),
        ),
        migrations.AddField(
            model_name='chain',
            name='relayer_enable_tenderly_simulation_before_relay',
            field=models.BooleanField(db_default=False, default=False, help_text='Enable/disable Tenderly simulation on the Safe Client Gateway when relaying a transaction on this chain.'),
        ),
    ]
