# SPDX-License-Identifier: FSL-1.1-MIT
# Generated by Django 6.0.5 on 2026-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0057_chain_relayer_sponsoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoken',
            name='priority',
            field=models.SmallIntegerField(default=100, help_text='A lower number indicates higher priority. Defaults to 100 (default ordering).'),
        ),
    ]
