# SPDX-License-Identifier: FSL-1.1-MIT
# Generated by Django 6.0.5 on 2026-06-16 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chains', '0058_gastoken_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteConfigReconcileRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_key', models.CharField(help_text='The Service.key this ref was last reconciled for.', max_length=255, unique=True)),
                ('ref', models.CharField(help_text='The Git ref (branch, tag, or SHA) last used.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
