# SPDX-License-Identifier: FSL-1.1-MIT
# Generated by Django 6.1.1 on 2026-09-29 11:21

import django.contrib.postgres.fields
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

# The options each relayer type already offers, so no chain changes behaviour
# on deploy. GTF and no relayer type map to none. SUBSCRIPTION is never
# inferred: it is set per chain by hand.
GAS_PAYMENT_OPTIONS_BY_RELAYER_TYPE = {
    "DAILY_LIMIT": ["FREE_DAILY_LIMIT"],
    "NO_FEE_CAMPAIGN": ["NO_FEE_CAMPAIGN"],
    "RELAY_FEE": ["PAY_FROM_SAFE"],
}


def fill_gas_payment_options(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    chain_model = apps.get_model("chains", "Chain")
    db_alias = schema_editor.connection.alias
    for relayer_type, options in GAS_PAYMENT_OPTIONS_BY_RELAYER_TYPE.items():
        chain_model.objects.using(db_alias).filter(relayer_type=relayer_type).update(
            relayer_gas_payment_options=options
        )


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0059_remove_contract_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='relayer_gas_payment_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FREE_DAILY_LIMIT', 'Free Daily Limit'), ('SUBSCRIPTION', 'Subscription'), ('PAY_FROM_SAFE', 'Pay From Safe'), ('NO_FEE_CAMPAIGN', 'No Fee Campaign')], max_length=32), blank=True, db_default=[], default=list, help_text='Ways the Safe Client Gateway may pay for a relayed transaction on this chain. Leave empty to offer none.'),
        ),
        migrations.AlterField(
            model_name='chain',
            name='relayer_safe_creation_sponsored',
            field=models.BooleanField(db_default=False, default=False, help_text='Sponsor/relay Safe account creation transactions. Requires a relayer type or a gas payment option.'),
        ),
        migrations.AlterField(
            model_name='chain',
            name='relayer_safe_transaction_sponsored',
            field=models.BooleanField(db_default=False, default=False, help_text='Deprecated: superseded by the gas payment options. Sponsor/relay Safe transaction execution. Requires a relayer type or a gas payment option.'),
        ),
        migrations.RunPython(fill_gas_payment_options, migrations.RunPython.noop),
    ]
