# Generated by Django 3.2 on 2021-04-28 13:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafeApp',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('icon_url', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('networks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
