# SPDX-License-Identifier: FSL-1.1-MIT
# Generated by Django 3.2.3 on 2021-05-27 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("safe_apps", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="safeapp",
            old_name="networks",
            new_name="chain_ids",
        ),
    ]
