# Generated by Django 3.2 on 2021-04-29 12:35

from django.db import migrations

DEFAULT_PROVIDERS = {
    ("1inch corporation", "https://1inch.exchange"),
    ("Aave", "https://aave.com"),
    ("Balancer Labs", "https://balancer.finance"),
    ("dHEDGE", "https://www.dhedge.org/"),
    ("Lido", "https://lido.fi"),
    ("Avo Labs", "https://avolabs.io/"),
    ("Request", "https://request.network"),
    ("Sablier", "https://sablier.finance"),
    ("Yearn Finance", "https://yearn.finance"),
}

DEFAULT_APPS = [
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmUXF1yVGdqUfMbhNyfM3jpP6Bw66cYnKPoWq6iHkhd3Aw",
        "name": "1inch.exchange",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmUXF1yVGdqUfMbhNyfM3jpP6Bw66cYnKPoWq6iHkhd3Aw/assets/1inch.png",
        "description": "DEX aggregator with the best prices on the market",
        "provided_by": "https://1inch.exchange",
        "networks": [
            1
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmQ3w2ezp2zx3u2LYQHyuNzMrLDJFjyL1rjAFTjNMcQ4cK",
        "name": "Aave",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmQ3w2ezp2zx3u2LYQHyuNzMrLDJFjyL1rjAFTjNMcQ4cK/aave.svg",
        "description": "Lend and borrow straight from your Gnosis Safe",
        "provided_by": "https://aave.com",
        "networks": [
            1
        ]
    },
    {
        "url": "https://app.aave.com/",
        "name": "Aave v2",
        "icon_url": "https://app.aave.com/aave.svg",
        "description": "Non-custodial liquidity protocol to earn interest on deposits and borrow",
        "networks": [
            1
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmRb2VfPVYBrv6gi2zDywgVgTg3A19ZCRMqwL13Ez5f5AS",
        "name": "Balancer Exchange",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmRb2VfPVYBrv6gi2zDywgVgTg3A19ZCRMqwL13Ez5f5AS/logo512.png",
        "description": "Exchange tokens using the Balancer DEX",
        "provided_by": "https://balancer.finance",
        "networks": [
            1
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmVaxypk2FTyfcTS9oZKxmpQziPUTu2VRhhW7sso1mGysf",
        "name": "Balancer Pool Management",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmVaxypk2FTyfcTS9oZKxmpQziPUTu2VRhhW7sso1mGysf/logo512.png",
        "description": "Manage liquidity on Balancer from your Gnosis Safe",
        "provided_by": "https://balancer.finance",
        "networks": [
            1
        ]
    },
    {
        "url": "https://safe-cmm.gnosis.io",
        "name": "Gnosis Custom Market Maker",
        "icon_url": "https://safe-cmm.gnosis.io/img/appIcon.svg",
        "description": "Allows you to deploy, withdraw and manage your custom market maker strategies",
        "networks": [
            4,
            100
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmX31xCdhFDmJzoVG33Y6kJtJ5Ujw8r5EJJBrsp8Fbjm7k",
        "name": "Compound",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmX31xCdhFDmJzoVG33Y6kJtJ5Ujw8r5EJJBrsp8Fbjm7k/Compound.png",
        "description": "Money markets on the Ethereum blockchain",
        "networks": [
            1,
            4
        ]
    },
    {
        "id": "{\"url\":\"https://app.dhedge.org/\",\"name\":\"dHEDGE\"}",
        "url": "https://app.dhedge.org/",
        "name": "dHEDGE",
        "icon_url": "https://app.dhedge.org/logo.svg",
        "description": "Decentralized asset management",
        "iconPath": "logo.svg",
        "provided_by": "https://www.dhedge.org/",
        "networks": [
            1
        ]
    },
    {
        "url": "https://app.ens.domains/",
        "name": "ENS App",
        "icon_url": "https://app.ens.domains/android-chrome-144x144.png",
        "description": "Decentralised naming for wallets, websites, & more.",
        "networks": [
            1,
            4
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmdCwUutYH8GXXNgTShB4cKJ8YJq4PqZ55QxMznKc9DbeS",
        "name": "Gnosis Auction Starter",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmdCwUutYH8GXXNgTShB4cKJ8YJq4PqZ55QxMznKc9DbeS/logo.svg",
        "description": "Safe app to start new auctions on Gnosis Auction",
        "networks": [
            1,
            4
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmTvrLwJtyjG8QFHgvqdPhcV5DBMQ7oZceSU4uvPw9vQaj",
        "name": "Idle v4",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmTvrLwJtyjG8QFHgvqdPhcV5DBMQ7oZceSU4uvPw9vQaj/logo.svg",
        "description": "Always the best yield, with no effort",
        "networks": [
            1,
            4
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/Qmde8dsa9r8bB59CNGww6LRiaZABuKaJfuzvu94hFkatJC",
        "name": "Lido Staking",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/Qmde8dsa9r8bB59CNGww6LRiaZABuKaJfuzvu94hFkatJC/logo.svg",
        "description": "Lido is the liquid staking solution for Ethereum.",
        "provided_by": "https://lido.fi",
        "networks": [
            1
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmYzTAH6Nzexu35tbWmhVrLYwWj9MdbD1iECejgaGHFk8P",
        "name": "Liquity Frontend",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmYzTAH6Nzexu35tbWmhVrLYwWj9MdbD1iECejgaGHFk8P/logo256.png",
        "description": "Simple frontend with high kickback rate, hosted on Arweave and ENS for maximal decentralisation.",
        "networks": [
            1,
            4
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmT96aES2YA9BssByc6DVizQDkofmKRErs8gJyqWipjyS8",
        "name": "Mushrooms Finance",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmT96aES2YA9BssByc6DVizQDkofmKRErs8gJyqWipjyS8/logo.png",
        "description": "Mushrooms Finance is a yield aggregator with focus on seeking sustainable profit",
        "networks": [
            1
        ]
    },
    {
        "id": "{\"url\":\"https://cloudflare-ipfs.com/ipfs/QmTa21pi77hiT1sLCGy5BeVwcyzExUSp2z7byxZukye8hr\",\"name\":\"P\"}",
        "url": "https://cloudflare-ipfs.com/ipfs/QmTa21pi77hiT1sLCGy5BeVwcyzExUSp2z7byxZukye8hr",
        "name": "PoolTogether",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmTa21pi77hiT1sLCGy5BeVwcyzExUSp2z7byxZukye8hr/pool-together.png",
        "description": "No-loss lotteries on your Gnosis Safe",
        "iconPath": "pool-together.png",
        "provided_by": "https://avolabs.io/",
        "networks": [
            1,
            4
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmTBBaiDQyGa17DJ7DdviyHbc51fTVgf6Z5PW5w2YUTkgR",
        "name": "Request",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmTBBaiDQyGa17DJ7DdviyHbc51fTVgf6Z5PW5w2YUTkgR/request_icon_green.svg",
        "description": "Create, receive and pay crypto invoices straight from your Gnosis Safe",
        "provided_by": "https://request.network",
        "networks": [
            1
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/Qmb1Xpfu9mnX4A3trpoVeBZ9sTiNtEuRoFKEiaVXWntDxB",
        "name": "Sablier",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/Qmb1Xpfu9mnX4A3trpoVeBZ9sTiNtEuRoFKEiaVXWntDxB/logo.svg",
        "description": "Safe App for interacting with the Sablier protocol",
        "provided_by": "https://sablier.finance",
        "networks": [
            1,
            4
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmXLxxczMH4MBEYDeeN9zoiHDzVkeBmB5rBjA3UniPEFcA",
        "name": "Synthetix",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmXLxxczMH4MBEYDeeN9zoiHDzVkeBmB5rBjA3UniPEFcA/Synthetix.png",
        "description": "Trade synthetic assets on Ethereum",
        "networks": [
            1,
            4
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmQovvfYYMUXjZfNbysQDUEXR8nr55iJRwcYgJQGJR7KEA",
        "name": "OpenZeppelin",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmQovvfYYMUXjZfNbysQDUEXR8nr55iJRwcYgJQGJR7KEA/openzeppelin.png",
        "description": "Securely manage and monitor your Ethereum project.",
        "networks": [
            1,
            4
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmZBgEvjqi9Jg8xATr9uUgNUVmnfYiECNxZv9Taux7mzgV",
        "name": "Transaction Builder",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmZBgEvjqi9Jg8xATr9uUgNUVmnfYiECNxZv9Taux7mzgV/tx-builder.png",
        "description": "A Safe app to compose custom transactions",
        "networks": [
            1,
            4,
            246,
            73799,
            100
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/QmX9B982ZAaBzbm6yBoZUS3uLgcizYA6wW65RCXVRZkG6f",
        "name": "WalletConnect",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/QmX9B982ZAaBzbm6yBoZUS3uLgcizYA6wW65RCXVRZkG6f/wallet-connect.svg",
        "description": "Allows your Gnosis Safe Multisig to connect to dapps via WalletConnect.",
        "networks": [
            1,
            4,
            246,
            73799,
            100
        ]
    },
    {
        "url": "https://cloudflare-ipfs.com/ipfs/Qme9HuPPhgCtgfj1CktvaDKhTesMueGCV2Kui1Sqna3Xs9",
        "name": "Yearn Vaults",
        "icon_url": "https://cloudflare-ipfs.com/ipfs/Qme9HuPPhgCtgfj1CktvaDKhTesMueGCV2Kui1Sqna3Xs9/logo.svg",
        "description": "Safe App for interacting with Yearn Vaults",
        "provided_by": "https://yearn.finance",
        "networks": [
            1
        ]
    }
]


def add_default_providers(apps, schema_editor):
    Provider = apps.get_model('safe_apps', 'Provider')
    for (name, url) in DEFAULT_PROVIDERS:
        Provider.objects.get_or_create(
            url=url,
            name=name,
        )


def add_default_apps(apps, schema_editor):
    Provider = apps.get_model('safe_apps', 'Provider')
    SafeApp = apps.get_model('safe_apps', 'SafeApp')

    for app in DEFAULT_APPS:
        try:
            provider = Provider.objects.get(url=app.get("provided_by"))
        except Provider.DoesNotExist:
            provider = None

        SafeApp.objects.get_or_create(
            url=app.get("url"),
            name=app.get("name"),
            icon_url=app.get("icon_url"),
            description=app.get("description"),
            networks=app.get("networks"),
            provider=provider
        )


class Migration(migrations.Migration):
    dependencies = [
        ('safe_apps', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_providers),
        migrations.RunPython(add_default_apps),
    ]
