# Generated by Django 3.2.4 on 2021-06-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safe_apps", "0004_add_auto_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="safeapp",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
