# Generated by Django 3.2.4 on 2021-07-02 12:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safe_apps", "0005_safeapp_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safeapp",
            name="chain_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveBigIntegerField(), size=None
            ),
        ),
    ]
