# Generated by Django 3.2.9 on 2021-12-13 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_apps', '0006_safeapp_chain_ids_big_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeapp',
            name='access_control_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='safeapp',
            name='access_control_type',
            field=models.CharField(choices=[('NO_RESTRICTIONS', 'No Restrictions'), ('DOMAIN_ALLOWLIST', 'Domain Allowlist')], default='NO_RESTRICTIONS', max_length=255),
        ),
    ]
