# Generated by Django 3.2.9 on 2021-12-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_apps', '0006_safeapp_chain_ids_big_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The domain URL client is hosted at', unique=True)),
                ('apps', models.ManyToManyField(blank=True, help_text='Apps that are enabled exclusively for this client', to='safe_apps.SafeApp')),
            ],
        ),
    ]
