# Generated by Django 3.2.9 on 2021-12-29 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safe_apps", "0006_safeapp_chain_ids_big_int"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="The domain URL client is hosted at",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "(?:(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}|\\[[0-9a-f:\\.]+\\]|([a-z¡-\uffff0-9](?:[a-z¡-\uffff0-9-]{0,61}[a-z¡-\uffff0-9])?(?:\\.(?!-)[a-z¡-\uffff0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z¡-\uffff-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?/?))(?::\\d{2,5})?\\Z",  # noqa: E501
                                code="invalid_hostname",
                                message="Enter a valid hostname (Without a resource path)",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="safeapp",
            name="exclusive_clients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Clients that are only allowed to use this SafeApp",
                to="safe_apps.Client",
            ),
        ),
    ]
