# Generated by Django 4.0.3 on 2022-04-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safe_apps", "0007_safeapp_access_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "safe_apps",
                    models.ManyToManyField(blank=True, to="safe_apps.safeapp"),
                ),
            ],
        ),
    ]
