# Generated by Django 4.1.5 on 2023-01-12 16:35
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safe_apps", "0008_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The unique name/key that identifies this feature",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "safe_apps",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Safe Apps where this feature is enabled.",
                        to="safe_apps.safeapp",
                    ),
                ),
            ],
        ),
    ]
