# Generated by Django 4.1.5 on 2023-01-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safe_apps", "0009_safe_apps_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="safeapp",
            name="developer_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SocialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("DISCORD", "Discord"),
                            ("GITHUB", "Github"),
                            ("TWITTER", "Twitter"),
                        ],
                        max_length=255,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "safe_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="safe_apps.safeapp",
                    ),
                ),
            ],
        ),
    ]
