# Generated by Django 4.2.2 on 2024-03-07 17:16

from django.db import migrations, models

import safe_apps.models


class Migration(migrations.Migration):
    dependencies = [
        ("safe_apps", "0010_safe_apps_social_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safeapp",
            name="icon_url",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=safe_apps.models.safe_app_icon_path,
                validators=[safe_apps.models.validate_safe_app_icon_size],
            ),
        ),
    ]
