# Generated by Django 5.0.6 on 2024-05-29 16:17

import safe_apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safe_apps", "0012_rename_visible_safeapp_listed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safeapp",
            name="icon_url",
            field=models.ImageField(
                max_length=255,
                upload_to=safe_apps.models.safe_app_icon_path,
                validators=[safe_apps.models.validate_safe_app_icon_size],
            ),
        ),
    ]
