# Generated by Django 5.0.6 on 2024-05-31 14:46

from django.db import migrations, models

import safe_apps.models


class Migration(migrations.Migration):

    dependencies = [
        ("safe_apps", "0013_assign_safeapp_icon_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safeapp",
            name="icon_url",
            field=models.ImageField(
                default="safe_apps/icon_url.jpg",
                max_length=255,
                upload_to=safe_apps.models.safe_app_icon_path,
                validators=[safe_apps.models.validate_safe_app_icon_size],
            ),
        ),
    ]
