# Generated by Django 5.0.6 on 2024-05-31 13:48
# Modified to update existing entries with no icon_url

from django.db import migrations, models

import safe_apps.models


def add_missing_default_icon_url(apps, schema_editor):
    SafeApp = apps.get_model("safe_apps", "SafeApp")
    default_icon_url = "safe_apps/icon_url.jpg"

    SafeApp.objects.filter(icon_url__isnull=True).update(icon_url=default_icon_url)
    SafeApp.objects.filter(icon_url="").update(icon_url=default_icon_url)


class Migration(migrations.Migration):

    dependencies = [
        ("safe_apps", "0013_alter_safeapp_icon_url"),
    ]

    operations = [
        migrations.RunPython(
            add_missing_default_icon_url, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="safeapp",
            name="icon_url",
            field=models.ImageField(
                default="safe_apps/icon_url.jpg",
                max_length=255,
                upload_to=safe_apps.models.safe_app_icon_path,
                validators=[safe_apps.models.validate_safe_app_icon_size],
            ),
        ),
    ]
