# Generated by Django 5.1.2 on 2024-11-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safe_apps", "0014_alter_safeapp_icon_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="safeapp",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
