# Generated by Django 5.1.4 on 2025-01-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safe_apps", "0015_safeapp_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprofile",
            name="platform",
            field=models.CharField(
                choices=[
                    ("DISCORD", "Discord"),
                    ("GITHUB", "Github"),
                    ("TWITTER", "Twitter"),
                    ("TELEGRAM", "Telegram"),
                ],
                max_length=255,
            ),
        ),
    ]
