# SPDX-License-Identifier: FSL-1.1-MIT
name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions: {}

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout reusable workflows
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: safe-global/github-reusable-workflows
          token: ${{ secrets.REUSABLE_WORKFLOWS_TOKEN }}
          path: reusable-workflows
          ref: 42b087a4e41013c8fe57e1aba8abbd5866a7be97
      - name: "CLA Assistant"
        uses: ./reusable-workflows/actions/cla
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          personal-access-token: ${{ secrets.CLA_ACCESS_TOKEN }}
          allowlist: moisses89,luarx,rmeissner,Uxio0,diegopazosrego,*bot
